### ISSUE TITLE
respond() doesn't take a function as its data argument

### ISSUE THREAD

**Issue by steph643** [SpringRoll/Bellhop#16]
In the source code, `respond()` is advertised as being able to take a function as its `data ` argument:
```javascript
/**
   *  A convience method for listening to an event and then responding with some data
   *  right away. Automatically removes the listener
   ...
   *  @param {Object} [data = {}] The object to pass back.
   *  	May also be a function; the return value will be sent as data in this case.
   ...
   */
respond(event, data = {}, runOnce = false) 
```
But it doesn't work. Only plain objects are supported.

This is too bad, as doing some dynamic computation before sending the data back is often required.

**Comment by steph643** [comment]
Workaround: return a plain object with one field initialized with the function call.
```javascript
bellhop.respond('init', {
  myData: (() => {
    // Computation here
    ....
    return result
  })()
})
```

**Comment by chipbell4** [comment]
You're absolutely right. This probably _should_ be a feature, and it looks like we intended to but forgot. We'll get that knocked out shortly and release a 2.4.0

**Comment by chipbell4** [comment]
This should be resolved now!
- It's tagged [here on github](https://github.com/SpringRoll/Bellhop/tree/2.4.0)
- It's also [published to npm](https://www.npmjs.com/package/bellhop-iframe)
