### ISSUE TITLE
Cannot send messages from the 'connected' handler

### ISSUE THREAD

**Issue by steph643** [SpringRoll/Bellhop#19]
When, from the main window, you send messages to an iframe from the `connected` handler, those messages are never received.

I think the reason lies here: https://github.com/SpringRoll/Bellhop/blob/master/src/Bellhop.js#L124. 

I believe this line should be moved to the end of `onConnectionReceived()`, so that messages sent from the `connected` handler are sent **after**: 1. The 'connected' message and 2. The waiting sends (so that the sending order is respected).

**Comment by chipbell4** [comment]
Should be fixed as of [2.4.1](https://github.com/SpringRoll/Bellhop/releases/tag/2.4.1)
