### ISSUE TITLE
Bellhop.disconnect() doesn't work

### ISSUE THREAD

**Issue by steph643** [SpringRoll/Bellhop#21]
If you disconnect and reconnect, you end up receiving each message twice. 

This is due to the fact that `Bellhop.disconnect()` doesn't release the event listener. Indeed, `addEventListener` (see [this line](https://github.com/SpringRoll/Bellhop/blob/master/src/Bellhop.js#L176)) and `removeEventListener` (see [this line](https://github.com/SpringRoll/Bellhop/blob/master/src/Bellhop.js#L202)) are not called on the same function.

**Comment by chipbell4** [comment]
Okay, this should be resolved now!
